@BankDashboard.Api_HostAddress = http://localhost:5062

GET {{BankDashboard.Api_HostAddress}}/api/bank-balances?currency=ILS&minAmount=100000&page=1&pageSize=50&sortBy=amount&sortDirection=desc
Accept: application/json

###

GET {{BankDashboard.Api_HostAddress}}/api/bank-balances/filters
Accept: application/json

###
